### ISSUE TITLE
Bug!!!

### ISSUE THREAD

**Issue by agiterman1** [ChenGabbay/Project1#1]
I **don't** like this project... pepe madge!!!

You shoud change:
```python
print("hello")
```
To:
```python
print("hello2")
```

**Comment by ChenGabbay** [comment]
```python
print("hello")
```

**Comment by ChenGabbay** [comment]
> I **don't** like this project... pepe madge!!!
> 
> You shoud change:
> 
> ```python
> print("hello")
> ```
> 
> To:
> 
> ```python
> print("hello2")
> ```

**Comment by ChenGabbay** [comment]
bywee
